github.com:
    users:
        4booser:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: 4booser
